default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: lapapappi-dev
  username: choon

test:
  <<: *default
  database: lapapappi-test

production:
  <<: *default
  database: lapapappi


